---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: docker-hub-credentials
  namespace: ci
spec:
  encryptedData:
    .dockerconfigjson: AgCcGu/uszIV+t6PcqZ3E1V/DGeVj+LcaN4jAkAHtTRMdtB01cuXW3f7NlKHDn5C17RnHrlqd+9XrnonRLM5NoUAUcXw7r+Q/UG9dymPe+uhEXMaO6oRltze5uGTCIrMegYVXpxkXElFjI9acZYPV3sHf2Kw5svqJ42DsWdPERejYTV85y/AfAasCQt78+jDGuPY1se4zdDq+bTGYbjFZ2ECpNseYoVO11pjOkBVGK2ZeYDcb68L7LD7X3h7TNfXSBwd7he/6Fxvi9PQ7vkfqY3mGWY7VrCsbgYB0w7bbyemCUs9106nXiRfRGlEBHUSkKrdecjPTUtHOesEvs80/8F6vBQcO/67A0qX3SC+14wfM+WLMooNJTmoWlbhxRwnVfO4oVjF3pAWST3cHRapENB2L8u37zX0TNRX4zFg1zs9I8WWgBdjebJD5bYrnyGHEeMGJ4g+G8HAdOTQRDPVArD9IHNPoPcL4D5ObZBJ0B0bWEXvghSY7KxWQWFbg1XucsHTBEkBz8NekLc8QEt6pxR+7LNr6PcQfvvOi4yiB8fNO1k1VvoF+s/T8cFF+XHovS/1Ywk8W0u2OW3vsIDj3b3qvpWZ4wgtCeGmb6KiHKtwr0la2MuMfgQamyy9CAQZ376GeS5T/D/WJFuvvK83JHGrQZOvHM6M/NehTr8uI0zOOUerPB90ux+w8us3iPDfiqrw45Ts5QKcKM0uzT+ELhkuQdspDpOGn6RmGKnIzArBu+wfrJKMD7ZSO/A15dlIpZll0w5EyX23OpqhU7ykfJ4h5zdcIwWDRlt3vitz5vP0btmGCtbbPSlPvY5eu9FuI+fETfOExalKJMlViZM/NGaJL0ObXjKs7piKnq8cWigp2sG0YD7cyH34X4uR+rdH6QMZfMRz2Gz7p++rMPu983tcUP2HukjdxRQdMbBL6eNTs/XLVwfVunbY7qU2Sr5XI2I=
  template:
    metadata:
      creationTimestamp: null
      name: docker-hub-credentials
      namespace: ci
    type: kubernetes.io/dockerconfigjson
