---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-webhook-secret
  namespace: ci
spec:
  encryptedData:
    secretToken: AgAMeuUvuRiO2JPEzgLFp7jdxQonY8FS1ntfRl7lNeWumfm2N4B31h+kRJDis6Gyi50sJNs57OQyiVnv7GFfXdd+tL2osnVPU4lgwcS0AIqlBGOpczcrxqgmpCXsNR2IqptVHivbWSR9BGeO/EsTX/HFUEFBcQY5Wsed5EPSLTxImTGaZpVrf0A/X1oxHTfJ6twF0I/JjX3kbXTbl37XZGw18D6d6V5e/aUWwQeQ7C3PjSqYIAfNEGSa80/oifVOl5n9YOWdz5yjkjITr1TrVws7WAXBHon+QAlM4i+g4KCo9au1l3C+HRX+PjrERtNH579VdqRk2MVub0t30nx46Vo3GdpMSA0eW5Mxhn48B2TnEZXVNvtGRoOnAvJ7xg5SFNihF2Rq8eUi0dhEMNb6f0XLURDNETH+Dam6zswnrtC42wwLdDaczlKjZEiBSPMcJjvQrbnm5UockMzQP3rn3oadbUkfetkFJMJC7vjeL1jHyPZwDhQZ1EBbGA57q/gQ+2bvC9+ddcBUezCTYsLiwk8RQkRIMdyottYOjmg2AlbzsnCuQxYYwwPfnoTUhS1yPRM6Qey8x0xq5Y7cSinNfsj6nN4onSQ7k0CD1/LpY7wuY2niPAjc4eu7Cju3R+sIOCq6juSupWr5blOeBzZYi9KDTdKTUhKqvRYon6DQWNJgKtoDv6X366dTMbEn6z0DQiKlyGbNrcNr1M3KhpcbcVrapsiRZ4jbFA0aloP1JdyqG0l/4HE6Wfp2NRt8YDBEBI4fMv4jrMGjH0RtRd4kjs7e
  template:
    metadata:
      creationTimestamp: null
      name: github-webhook-secret
      namespace: ci
