apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: git-clone
  namespace: ci
spec:
  params:
    - name: url
      description: URL del repo
    - name: revision
      description: rama o commit
      default: main
  workspaces:
    - name: source
      description: workspace donde se clona
  steps:
    - name: clone
      image: alpine/git:2.43.0
      script: |
        #!/bin/sh
        set -e
        cd $(workspaces.source.path)
        git clone --depth 1 --branch $(params.revision) $(params.url) .
        echo "Cloned $(params.url) at $(params.revision)"
        git log -1 --oneline
