apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: install-deps
  namespace: tekton-pipelines
spec:
  params:
    - name: workdir
      description: subdirectorio (api o worker)
      default: api
  workspaces:
    - name: source
  steps:
    - name: npm-ci
      image: node:20-alpine
      workingDir: $(workspaces.source.path)/$(params.workdir)
      script: |
        #!/bin/sh
        set -e
        npm ci --no-audit --no-fund
        echo "Deps instaladas"
