apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: micrositio
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: nfs-csi
  resources:
    requests:
      storage: 1Gi
