apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: micrositio-build-dh-
  namespace: ci
spec:
  pipelineRef:
    name: micrositio-build
  params:
    - name: image-api-mirror
      value:
        - '--destination=docker.io/sebasco3547/micrositio-api:latest'
    - name: image-worker-mirror
      value:
        - '--destination=docker.io/sebasco3547/micrositio-worker:latest'
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes: [ReadWriteOnce]
          resources:
            requests:
              storage: 3Gi
          storageClassName: nfs-csi
