# Dispara el pipeline CI: kubectl create -f tekton/pipelinerun-example.yaml
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: micrositio-build-
  namespace: ci
spec:
  pipelineRef:
    name: micrositio-build
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes: [ReadWriteOnce]
          resources:
            requests:
              storage: 3Gi
          storageClassName: nfs-csi
