apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-redis-auth
  namespace: micrositio
spec:
  secretTargetRef:
    - parameter: password
      name: redis-auth
      key: REDIS_PASSWORD
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: worker-scaler
  namespace: micrositio
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: worker
  pollingInterval: 10
  cooldownPeriod: 60
  minReplicaCount: 1
  maxReplicaCount: 5
  triggers:
    - type: redis
      metadata:
        address: redis.micrositio.svc.cluster.local:6379
        listName: bull:notificaciones:wait
        listLength: "5"
      authenticationRef:
        name: keda-redis-auth
    - type: redis
      metadata:
        address: redis.micrositio.svc.cluster.local:6379
        listName: bull:delivery:wait
        listLength: "3"
      authenticationRef:
        name: keda-redis-auth
    - type: redis
      metadata:
        address: redis.micrositio.svc.cluster.local:6379
        listName: bull:webhook-delivery:wait
        listLength: "10"
      authenticationRef:
        name: keda-redis-auth
