# ═══════════════════════════════════════════════════════════════════
# Credenciales de usuarios MongoDB (root, app, worker)
# Cifrar con kubeseal antes de committear
# ═══════════════════════════════════════════════════════════════════
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-users
  namespace: micrositio
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: root
  MONGO_INITDB_ROOT_PASSWORD: changeme-root-strong-password
  APP_USER: app
  APP_PASSWORD: changeme-app-strong-password
  WORKER_USER: worker
  WORKER_PASSWORD: changeme-worker-strong-password
