# Helm values para kube-prometheus-stack
prometheus:
  prometheusSpec:
    retention: 7d
    resources:
      requests: { cpu: 200m, memory: 512Mi }
      limits: { cpu: 1000m, memory: 1Gi }
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: nfs-csi
          accessModes: [ReadWriteOnce]
          resources:
            requests:
              storage: 10Gi
    # Permitir scraping de servicios en otros namespaces
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false

grafana:
  enabled: true
  adminPassword: 'admin-cambiar-en-produccion'
  persistence:
    enabled: true
    storageClassName: nfs-csi
    size: 5Gi
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Loki
          type: loki
          access: proxy
          url: http://loki.observability.svc.cluster.local:3100
        - name: Prometheus
          type: prometheus
          access: proxy
          url: http://kps-kube-prometheus-stack-prometheus.observability.svc.cluster.local:9090
          isDefault: true
  service:
    type: ClusterIP
    port: 80
  resources:
    requests: { cpu: 100m, memory: 256Mi }
    limits: { cpu: 500m, memory: 512Mi }

alertmanager:
  alertmanagerSpec:
    retention: 120h
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: nfs-csi
          accessModes: [ReadWriteOnce]
          resources:
            requests:
              storage: 1Gi

# No necesitamos exporters para nodos en este lab
nodeExporter:
  enabled: true
kubeStateMetrics:
  enabled: true
