apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argocd
  namespace: argocd
  labels:
    release: kps
spec:
  namespaceSelector:
    matchNames: [argocd]
  selector:
    matchExpressions:
      - key: app.kubernetes.io/part-of
        operator: In
        values: [argocd]
  endpoints:
    - port: metrics
      interval: 30s
