# ═══════════════════════════════════════════════════════════════════
# ClusterIssuer self-signed (firma a si mismo)
# Usado solo para crear el certificado raiz CA
# ═══════════════════════════════════════════════════════════════════
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-bootstrap
spec:
  selfSigned: {}
