apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tekton-listener
  namespace: ci
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
spec:
  ingressClassName: nginx
  rules:
    - host: tekton.zuyu.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: el-micrositio-github-listener
                port:
                  number: 8080
