apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: micrositio-build-template
  namespace: ci
spec:
  params:
    - name: git-revision
      description: SHA del commit a construir
      default: main
    - name: git-repo-url
      description: URL del repo a clonar
      default: https://github.com/SEBASTIANCONTRERAS35/micrositio-pedidos.git
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        generateName: micrositio-build-auto-
        namespace: ci
      spec:
        pipelineRef:
          name: micrositio-build
        params:
          - name: revision
            value: $(tt.params.git-revision)
          - name: repo-url
            value: $(tt.params.git-repo-url)
          - name: image-api-mirror
            value:
              - '--destination=docker.io/sebasco3547/micrositio-api:latest'
          - name: image-worker-mirror
            value:
              - '--destination=docker.io/sebasco3547/micrositio-worker:latest'
        workspaces:
          - name: source
            volumeClaimTemplate:
              spec:
                accessModes: [ReadWriteOnce]
                resources:
                  requests:
                    storage: 3Gi
                storageClassName: nfs-csi
