apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: worker-metrics
  namespace: observability
  labels:
    release: kps
spec:
  namespaceSelector:
    matchNames: [micrositio]
  selector:
    matchLabels:
      app: worker
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
